#!/usr/bin/env node
/* Project Navigator builder. Source of truth is the modular source tree.
   RELEASE_VERSION is the single internal version authority for the dist filename, HTML title,
   and bundle marker. Do not rename built HTML after generation; change RELEASE_VERSION instead. */
'use strict';
const fs=require('fs'),path=require('path');
const ROOT=__dirname,args=process.argv.slice(2);
const getArg=(flag,fallback)=>{const i=args.indexOf(flag);return i>=0&&args[i+1]?args[i+1]:fallback;};
const RELEASE_VERSION='V46.1.1';
const VERSION=getArg('--version',RELEASE_VERSION),CHECK_ONLY=args.includes('--check'),SHELL='index.html';
const OUT=getArg('--out',path.join('dist',`project-navigator_${VERSION}.html`));
const CSS=['components.css','components.v4439-overrides.css','components.page5-region.css','components.visual-examples.css','components.v45.7.3.css','components.project-navigation.css','components.simulated-document-check.css'];
const JS=[
'data.js','data/insight-catalog.js','data/public-service-resources.js','data/advisor-scenarios.js','data/customer-language-map.js','data/customer-option-labels.js','data/visual-example-catalog.js','data/learning-card-registry.js','data/progressive-visual-rules.js','data/progressive-insights.js','data/document-guidance-catalog.js','data/document-reference-examples.js','data/simulated-document-fixtures.js','data/visual-guidance-catalog.js','data/visual-guidance-map.js','data/planning-benchmark-catalog.js','data/v45.7-rule-contracts.js','data/v45.7-glossary-additions.js','data/answer-response-catalog.js','data/shadow-rule-catalog.js','data/canonical-shadow-catalog.js','data/governed-shadow-catalog.js','state.js',
'core/insight-engine.js','core/insight-view-model.js','core/insight-asset-resolver.js','core/experience-assembler.js','core/insight-instrumentation.js','core/answer-state-model.js','core/provenance-model.js','core/state-compatibility.js','core/source-rule-registry.js','core/jadu-conflict-control.js','core/shadow-rule-model.js','core/canonical-shadow-model.js','core/governed-shadow-evaluator.js','core/recomputation-pipeline.js','core/persistence-reconstruction.js','core/document-guidance-engine.js','core/visual-guidance-view-model.js','core/v45.7-correctness-engine.js','core/v45.7-service-context-engine.js','core/question-inline-response-engine.js','core/planning-benchmark-view-model.js',
'components/generated-canonical-inventory.js','core/planning-reference-model.js','core/guidance-model.js',
'exports/application-draft.js','exports/application-draft-validation.js','exports/application-export-manifest.js','exports/application-reviewed-export-plan.js',
'core/icons.js','core/recognition.js','core/recognition-contract.js','core/preparation-context.js','core/arrival-scenes.js','components/arrival-walkthrough.js',
'components/component-registry.js','components/contextual-question-response.js','components/fast-facts-document-gallery.js','components/fast-facts-sections.js','components/fast-facts-workspace.js','components/generated-glossary-data.js','components/generated-comprehension-data.js','components/question-help.js','components/glossary-component.js','components/summary-density.js','components/planning-reference.js','components/planning-benchmark-card.js','components/guidance-workspace.js','components/visual-examples.js','components/explainable-insight-card.js','components/visual-guidance-card.js','components/document-guidance-card.js','components/simulated-document-check.js','components/v45.7-correctness-guidance.js','components/question-inline-response.js','components/image-viewer.js','components/fast-insights.js',
'screens/screen-shared.js','screens/screen-arrival-selector.js','screens/screen-entry-website.js','screens/screen-entry-email.js','screens/screen-entry-assistant.js','screens/screen-arrival-debug.js','screens/screen-start.js','screens/screen-questions.js','screens/screen-understanding.js','screens/screen-decisions.js','screens/screen-export-review.js','screens/screen-cost-tiers.js','screens/screen-summary.js',
'core/customer-language.js','core/navigation-model.js','components/project-navigation.js','core/render.js','core/summary-text.js','core/advisor.js','core/advisor-content-adapter.js','core/events.js','core/v45.7-intake-simplification.js','core/v45.7-navigation-scenario-guide.js','core/v45.7.5.9.4-scenario-guide-runtime.js','core/v45.7-glossary-runtime.js','core/v45.8.3-question-nav-scroll.js','core/v45.8.5-global-horizontal-scroll.js','core/v45.8.7-summary-accordions.js'];
const PROHIBITED=[/readiness_scoring/i,/score_formula/i,/load_document_deadline_days/i,/R\.LOAD_DEADLINE/,/\bRAG\s*score\b/i,/\bproject readiness\b/i,/\bapplication readiness\b/i,/\bapproval likelihood\b/i,/\bcompletion percentage\b/i,/\bpercent complete\b/i,/\bdue date\b/i,/pge-my\.sharepoint\.com/i,/pge\.sharepoint\.com/i];
function read(rel){const p=path.join(ROOT,rel);if(!fs.existsSync(p))throw new Error('MISSING SOURCE: '+rel);return fs.readFileSync(p,'utf8');}
function exists(rel){return fs.existsSync(path.join(ROOT,rel));}
function stripComments(s){return String(s).replace(/\/\*[\s\S]*?\*\//g,'').replace(/<!--[\s\S]*?-->/g,'');}
function duplicate(items){const seen=new Set(),dupes=[];for(const x of items){if(seen.has(x))dupes.push(x);seen.add(x);}return dupes;}
function normalize(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ').replace(/[’‘]/g,"'");}
function inventoryChecks(){const e=[];[SHELL,...CSS,...JS].forEach(f=>{if(!exists(f))e.push('missing source: '+f);});duplicate(JS).forEach(f=>e.push('duplicate JS module: '+f));duplicate(CSS).forEach(f=>e.push('duplicate CSS module: '+f));return e;}
function structChecks(){const e=[];if(!exists('scenarios.json'))return ['scenarios.json missing'];let m;try{m=JSON.parse(read('scenarios.json'));}catch(err){return ['scenarios.json invalid: '+err.message];}if('readiness_scoring' in m)e.push('top-level readiness_scoring present');if(m.meta&&m.meta.universal&&'load_document_deadline_days' in m.meta.universal)e.push('universal load deadline present');if((m.rules||[]).some(r=>r.id==='R.LOAD_DEADLINE'))e.push('R.LOAD_DEADLINE present');return e;}
function glossaryChecks(){const e=[];let g,c;try{g=JSON.parse(read('echo_scope_glossary.json'));c=JSON.parse(read('data/comprehension-content.json'));}catch(err){return ['glossary source invalid: '+err.message];}
 const ids=new Set(),labels=new Map(),aliases=new Map();
 (g.GLOSSARY||[]).forEach(x=>{if(ids.has(x.id))e.push('duplicate canonical glossary ID: '+x.id);ids.add(x.id);const lk=normalize(x.term);if(labels.has(lk))e.push('duplicate normalized glossary label: '+x.term);labels.set(lk,x.id);[x.term].concat(x.aliases||[]).forEach(a=>{const k=normalize(a),owner=aliases.get(k);if(owner&&owner!==x.id)e.push('conflicting glossary alias: '+a);aliases.set(k,x.id);});});
 const cids=new Set(),caliases=new Map();(c.records||[]).forEach(x=>{if(cids.has(x.id))e.push('duplicate comprehension ID: '+x.id);cids.add(x.id);[x.displayTerm].concat(x.aliases||[]).forEach(a=>{const k=normalize(a),owner=caliases.get(k);if(owner&&owner!==x.id)e.push('conflicting comprehension alias: '+a);caliases.set(k,x.id);});});
 if(!read('scripts/build-glossary.js').includes('Duplicate canonical glossary ID'))e.push('canonical glossary generator guard missing');
 if(!read('components/glossary-component.js').includes('canonicalEntries'))e.push('canonical glossary merge missing');
 if(!read('screens/screen-shared.js').includes('GlossaryController.entries'))e.push('glossary modal is not using canonical entries');
 return e;}
function integrationChecks(){const e=[];
 try{const arc=require('./data/answer-response-catalog.js'),dgc=require('./data/document-guidance-catalog.js'),ref=require('./data/document-reference-examples.js');const ids=new Set(Object.values(dgc.documents).map(d=>d.id));arc.validate().forEach(x=>e.push('answer-response '+x));arc.rows.forEach(r=>r.documentGuidanceKeys.forEach(k=>{if(!dgc.documents[k])e.push('answer-response '+r.responseId+' unknown document key '+k);}));Object.keys(ref).forEach(k=>{if(!ids.has(k))e.push('reference example for unknown document '+k);});}catch(err){e.push('answer-response catalog invalid: '+err.message);}const markers=[
 ['data/public-service-resources.js','PUBLIC_SERVICE_RESOURCES'],['data/advisor-scenarios.js','ADVISOR_SCENARIOS'],['data/customer-language-map.js','V44.49.60 GOVERNED CUSTOMER LANGUAGE MAP'],['data/customer-option-labels.js','V44.49.61 CUSTOMER LABEL COMPATIBILITY'],['core/customer-language.js','CustomerLanguage'],['core/advisor-content-adapter.js','AdvisorContentAdapter']];markers.forEach(([f,m])=>{if(exists(f)&&!read(f).includes(m))e.push('missing marker in '+f+': '+m);});
 if(!read('data/customer-option-labels.js').includes('q.options=q.options.map'))e.push('customer option labels not connected to canonical question options');
 if(!read('core/advisor-content-adapter.js').includes('pnRespond=function'))e.push('advisor scenario runtime wrapper missing');
 if(read('screens/screen-export-review.js').includes('Draft review only.'))e.push('obsolete draft review boundary remains');
 return e;}
function prohibitedHits(){const hits=[];[SHELL,...CSS,...JS].forEach(f=>{if(!exists(f))return;const active=stripComments(read(f));PROHIBITED.forEach(rx=>{const m=active.match(rx);if(m)hits.push(`text ${f} ${rx} -> "${m[0]}"`);});});return hits;}
function buildStyles(){return CSS.map(f=>`/* ===== ${f} ===== */\n${read(f)}`).join('\n');}
function buildScripts(){return JS.map(f=>`/* ===== ${f} (data-inlined-from="${f}") ===== */\n${read(f)}`).join('\n;\n');}
function safeScript(s){return String(s).replace(/<\/script/gi,'<\\/script').replace(/<!--/g,'<\\!--');}
function assemble(){let h=read(SHELL).replace(/<script\b[^>]*\bsrc\s*=\s*["'][^"']+["'][^>]*>\s*<\/script>\s*/gi,'');const styles=`<style>\n${buildStyles()}\n</style>`,scripts=`<script>\n${safeScript(buildScripts())}\n</script>`;const sb=/<style\b[^>]*>\s*<!--STYLES-->[\s\S]*?<!--\/STYLES-->\s*<\/style>/i,jb=/<script\b[^>]*>\s*<!--SCRIPTS-->[\s\S]*?<!--\/SCRIPTS-->\s*<\/script>/i;h=sb.test(h)?h.replace(sb,styles):h.replace(/<!--STYLES-->[\s\S]*?<!--\/STYLES-->/,styles);h=jb.test(h)?h.replace(jb,scripts):h.replace(/<!--SCRIPTS-->[\s\S]*?<!--\/SCRIPTS-->/,scripts);h=h.replace(/<title>[\s\S]*?<\/title>/,`<title>StartRight | ${VERSION}</title>`);h=h.replace('</head>',`<!-- Version ${VERSION} single-file bundle. Source of truth is the modular tree. -->\n</head>`);return h;}
function artifactChecks(h){const e=[];const shell=read(SHELL);if(!/<\/html>\s*$/i.test(shell))e.push('shell contains trailing content after closing html');if(!/<\/html>\s*$/i.test(h))e.push('artifact contains trailing content after closing html');if(/(?:^|\n)\s*File:\s*components\.visual-examples\.css\b/i.test(shell))e.push('flattened source marker leaked into shell');if(/<script\b[^>]*\bsrc\s*=/i.test(h))e.push('external script reference remains');if(!h.includes(VERSION))e.push('artifact version missing');if(!h.includes('GlossaryController.entries'))e.push('canonical glossary runtime missing');if(/pge-my\.sharepoint\.com|pge\.sharepoint\.com/i.test(h))e.push('internal SharePoint URL present');return e;}
function gate(h){return [...inventoryChecks().map(x=>'inventory '+x),...structChecks().map(x=>'struct '+x),...integrationChecks().map(x=>'workspace '+x),...glossaryChecks().map(x=>'glossary '+x),...prohibitedHits(),...artifactChecks(h).map(x=>'build '+x)];}
function main(){try{require('./core/shadow-rule-model.js').validate(require('./data/shadow-rule-catalog.js'));}catch(err){console.error('SHADOW CATALOG INVALID: '+err.message);process.exit(1);}try{require('./core/canonical-shadow-model.js').validateCatalog(require('./data/canonical-shadow-catalog.js'));}catch(err){console.error('CANONICAL SHADOW CATALOG INVALID: '+err.message);process.exit(1);}try{var canonical=require('./core/canonical-shadow-model.js');var facts=Object.keys(canonical.derive({projectType:'panel',answers:{}}).facts);require('./core/governed-shadow-evaluator.js').validate(require('./data/governed-shadow-catalog.js'),facts);}catch(err){console.error('GOVERNED SHADOW CATALOG INVALID: '+err.message);process.exit(1);}let html;try{html=assemble();}catch(err){console.error('\n✗ BUILD INPUT ERROR:\n  '+err.message);process.exit(1);}const errors=gate(html);if(errors.length){console.error(`\n✗ ${CHECK_ONLY?'GUARDRAIL FAIL':'BUILD FAILED'}:\n  `+errors.join('\n  '));process.exit(1);}if(CHECK_ONLY){console.log('✓ guardrail check PASS (no output written)');return;}const out=path.resolve(ROOT,OUT);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,html);console.log('✓ build OK');console.log('  version :',VERSION);console.log('  output  :',OUT);console.log('  guardrail: PASS (inventory + V44.49.62 canonical glossary)');}
main();
