'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const R=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(R,f),'utf8');function load(f){const c={};vm.runInNewContext(read(f),c);return c;}const E=load('core/v45.7-service-context-engine.js').V457ServiceContextEngine,G=load('data/v45.7-glossary-additions.js').V457_GLOSSARY_ADDITIONS;
test('panel capacity selection never establishes service adequacy',()=>{const x=E.servicePotential({projectType:'panel',panelIntent:'Increase the panel capacity',panelProposedCapacity:'400 amps or more'});assert.equal(x.serviceUpgradePotential,true);assert.equal(x.panelAdequacyEstablished,false);assert.equal(x.serviceAdequacyEstablished,false);assert.match(x.text,/does not establish/);});
test('underground/trenching context requires both service-upgrade potential and underground service',()=>{assert.equal(E.underground({projectType:'panel',panelIntent:'Increase the panel capacity',panelServiceMethod:'Overhead service'}).status,'not-applicable');assert.equal(E.underground({projectType:'panel',panelIntent:'Replace the panel at the same capacity',panelServiceMethod:'Underground service'}).status,'not-applicable');const x=E.underground({projectType:'panel',panelIntent:'Increase the panel capacity',panelServiceMethod:'Underground service'});assert.equal(x.status,'eligible');assert.equal(x.trenchingRequired,false);});
test('underground copy remains conditional and disclaims site/engineering review',()=>{const x=E.underground({projectType:'panel',panelIntent:'Increase the panel capacity',panelServiceMethod:'Underground service'});assert.match(x.text,/may be required/i);assert.match(x.text,/if an underground service upgrade is necessary/i);assert.match(x.text,/depend on.*design and review/i);assert.equal(x.siteReviewPerformed,false);assert.equal(x.engineeringReviewPerformed,false);});
test('AHJ and PG&E load information cannot substitute',()=>{const x=E.loadDistinction({panelIntent:'Add electrical equipment; panel change not decided',panelLoads:['EV charger']});assert.equal(x.status,'eligible');assert.equal(x.ahjSatisfiesPgAndELoad,false);assert.match(x.text,/does not establish that the other is complete/i);});
test('JADU and ADU glossary entries are published with governed boundaries',()=>{const p=G.published(),ids=p.map(x=>x.id);assert.ok(ids.includes('accessory-dwelling-unit-v457'));assert.ok(ids.includes('junior-accessory-dwelling-unit-v457'));const j=p.find(x=>x.id==='junior-accessory-dwelling-unit-v457');
  // 2026-10-03 (P0.1): "not required" implied optionality; corrected to the canonical prohibition.
  assert.match(j.definition,/cannot be separately metered/i);assert.doesNotMatch(j.definition,/is not required to have a separate meter/i);assert.match(j.definition,/does not by itself determine/i);});
test('Utility/Civil Plan remains candidate and is not registered at runtime',()=>{const x=G.rows.find(x=>x.id==='utility-civil-plan-candidate');assert.equal(x.publicationStatus,'candidate-not-published');assert.ok(!G.published().some(x=>x.id===x.id&&x.id==='utility-civil-plan-candidate'));});
test('customer guidance renderer consumes the governed service engine',()=>{const s=read('components/v45.7-correctness-guidance.js');assert.match(s,/V457ServiceContextEngine\.servicePotential/);assert.match(s,/V457ServiceContextEngine\.underground/);assert.match(s,/V457ServiceContextEngine\.loadDistinction/);});
test('loads service context before the guidance renderer',()=>{const b=read('build.js');assert.ok(b.indexOf('core/v45.7-service-context-engine.js')<b.indexOf('components/v45.7-correctness-guidance.js'));assert.ok(b.indexOf('data/v45.7-glossary-additions.js')<b.indexOf('core/v45.7-glossary-runtime.js'));});
// Retired 2026-10-03: the RELEASE_VERSION='V45.7.4' pin is superseded now the build is on V45.7.5.9.9.
test('service context remains pure and introduces no persistence or workflow state',()=>{const s=read('core/v45.7-service-context-engine.js');assert.doesNotMatch(s,/localStorage|sessionStorage|scheduleDraftSave|persistDraft|progressPercent|readiness|completedSections|S\./);});
