'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const R=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(R,f),'utf8');
test('property remains virtual and Energy Needs is filtered, not reindexed out of source data',()=>{const s=read('core/v45.7-intake-simplification.js');assert.match(s,/q&&q\.id!==\'energy\'/);assert.match(s,/baseQuestions\(projectType\)\.filter/);assert.doesNotMatch(read('state.js'),/delete .*property/);});
test('default is exact eligible canonical value and carries prototype provenance',()=>{const s=read('state.js');assert.match(s,/DEFAULT_RESIDENTIAL_PROPERTY="Single-family home"/);assert.match(s,/S\.answerSources\.property="prototype-default"/);assert.match(s,/answerSources:S\.answerSources\|\|\{\}/);assert.match(s,/S\.answerSources=d\.answerSources\|\|\{\}/);});
test('default is removed from customer-known summary',()=>{const s=read('state.js');assert.match(s,/knownValues=knownValues\.concat\(\[a\.timing\]\)/);assert.doesNotMatch(s,/knownValues=knownValues\.concat\(\[a\.property,a\.energy,a\.timing\]\)/);});
test('legacy energy no longer drives current state interpretation',()=>{const s=read('state.js');assert.match(s,/function derivedEnergyNeed/);assert.match(s,/var resolved=!notSure\(derivedEnergyNeed\(a\)\)/);assert.doesNotMatch(s,/a\.energy==="More electrical capacity"/);});
test('project continue starts loading and never opens property choices',()=>{const s=read('core/v45.7-intake-simplification.js');assert.match(s,/actions\['project-continue'\]/);assert.match(s,/startFastFactsLoading/);const q=read('screens/screen-questions.js');assert.match(q,/Preparing your project guidance/);assert.doesNotMatch(q,/body=fastFactsPropertyChoices\(\)/);});
test('Fast Facts Continue contract remains index 1 while Previous contract remains virtual results',()=>{const q=read('screens/screen-questions.js'),runtime=read('core/v45.7-intake-simplification.js');assert.match(runtime,/questionIndex=0/);assert.match(runtime,/fastFactsPhase="results"/);assert.match(q,/fastFactsResults/);});
test('project choice copy matches actual destination',()=>{const s=read('screens/screen-start.js');assert.match(s,/See fast facts/);assert.match(s,/review fast facts before the focused questions/);assert.doesNotMatch(s,/Continue to questions/);});
test('default property is exported with prototype-default provenance',()=>{const s=read('core/v45.7-intake-simplification.js');assert.match(s,/provenance:'prototype-default'/);assert.match(s,/source:'answers\.property'/);});
test('unsupported project types cannot receive the residential default',()=>{const s=read('state.js');assert.match(s,/S\.projectType!=="adu"&&S\.projectType!=="panel"/);});
test('final adapter runs after events',()=>{const b=read('build.js');assert.ok(b.indexOf('core/events.js')<b.indexOf('core/v45.7-intake-simplification.js'));});
// Retired 2026-10-03: the RELEASE_VERSION='V45.7.2' pin is superseded now the build is on V45.7.5.9.9.
