'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const R=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(R,f),'utf8');function ctx(){const c={};vm.runInNewContext(read('core/v45.7-correctness-engine.js'),c);return c;}const C=ctx().V457CorrectnessEngine;
/* Retired 2026-10-03: AC-01/AC-02 asserted JADU metering as merely "not required" / "not established
   by rule 18". V45.7.5.8 deliberately tightened this to an explicit, canonical ineligibility
   determination (separateMeterEligible:false, separateMeterEligibility:'ineligible', meteringText
   "A Junior ADU cannot be separately metered.") — see tests/v45.7.5.8-correctness-closure.test.js
   "canonical JADU evaluation explicitly fails separate meter eligibility closed", which is the
   live contract and directly contradicts the old doesNotMatch(/cannot/i) assertion here. */
test('AC-03 detached confirmed contradiction is incompatible',()=>{const x=C.aduCompatibility({aduType:'Detached ADU',aduAddressStatus:'No separate address is assigned',aduMeterServiceIntent:'Add a separate service connection'});assert.equal(x.status,'incompatible');assert.equal(x.reasonCode,'DETACHED_ADU_SECOND_SERVICE_ADDRESS_CONFLICT');assert.equal(x.suppressAffirmativeServiceGuidance,true);});
test('AC-04 contradiction remains non-blocking and non-determinative',()=>{const x=C.aduCompatibility({aduType:'Detached ADU',aduAddressStatus:'No separate address is assigned',aduMeterServiceIntent:'Add a separate service connection'});assert.equal(x.allowNext,true);assert.equal(x.needsConfirmation,true);assert.equal(x.automaticApproval,false);assert.equal(x.automaticDenial,false);});
test('R-06 unknown address remains unresolved, not no',()=>{const x=C.aduCompatibility({aduType:'Detached ADU',aduAddressStatus:"I’m not sure",aduMeterServiceIntent:'Add a separate service connection'});assert.equal(x.status,'unresolved');assert.equal(x.reasonCode,'ADDRESS_UNCONFIRMED');});
test('AC-05 panel permit semantics are scenario-specific and non-solar when solar absent',()=>{const x=C.permit({projectType:'panel',panelLoads:[]});assert.match(x.pgAndEIntakeText,/not required for PG&E records/i);assert.match(x.meterSetText,/local-jurisdiction permit may be needed later/i);assert.equal(x.solarSpecificReasoningAllowed,false);});
test('AC-10 AHJ information never satisfies PG&E load information',()=>{const x=C.load({projectType:'panel',panelIntent:'Add electrical equipment; panel change not decided',panelLoads:['EV charger']});assert.equal(x.status,'eligible');assert.equal(x.ahjSatisfiesPgAndELoad,false);});
test('state integrates the governed contradiction into existing consistency findings',()=>{const s=read('state.js');assert.match(s,/V457CorrectnessEngine\.aduCompatibility/);assert.match(s,/adu-detached-address-service-conflict/);assert.match(s,/\["aduType","aduAddressStatus","aduMeterServiceIntent"\]/);});
test('question screen renders central correctness guidance and retains existing consistency notice',()=>{const s=read('screens/screen-questions.js');assert.match(s,/V457CorrectnessGuidance\.forQuestion/);assert.match(s,/consistencyNotice \+ qFlagNotice/);});
test('build exposes new modules before their consumers',()=>{const b=read('build.js');assert.match(b,/data\/v45\.7-rule-contracts\.js/);assert.match(b,/core\/v45\.7-correctness-engine\.js/);assert.match(b,/components\/v45\.7-correctness-guidance\.js/);assert.ok(b.indexOf('core/v45.7-correctness-engine.js')<b.indexOf('screens/screen-questions.js'));});
