'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const R=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(R,f),'utf8');
test('selected-answer contract keeps meaning primary and details collapsed',()=>{const s=read('components/question-inline-response.js');assert.ok(s.includes('data-density-contract="answer-primary-details"'));assert.ok(s.includes('inline-response__definition'));assert.ok(s.includes('details class=\"inline-response__details inline-response__documents\"'));assert.ok(s.includes('details class=\"inline-response__details inline-response__prepare\"'));assert.doesNotMatch(s,/inline-response__documents\\" open/);});
test('documents and practical next step remain eligible independent of disclosure state',()=>{const s=read('components/question-inline-response.js');assert.ok(s.includes('if(!m.documents||!m.documents.length)return'));assert.ok(s.includes("m.preparation?"));assert.doesNotMatch(s,/localStorage|sessionStorage|persistDraft|scheduleDraftSave/);});
test('same response still suppresses duplicate reference rendering',()=>{const s=read('components/question-inline-response.js');assert.ok(s.includes("shared?'':references(m)"));assert.ok(s.includes('VisualGuidanceMap.combined'));});
test('Fast Facts gives recommended action a primary hierarchy and supporting sections a restrained hierarchy',()=>{const s=read('components/fast-facts-workspace.js');assert.ok(s.includes('data-priority="primary"'));assert.ok(s.includes('data-hierarchy="supporting"'));const css=read('components.visual-examples.css');assert.ok(css.includes('.ff-recommended[data-priority="primary"]'));assert.ok(css.includes('.ff-section[data-hierarchy="supporting"]'));});
test('provenance vocabulary distinguishes fact interpretation and confirmation',()=>{const css=read('components.visual-examples.css');assert.ok(css.includes('Known fact'));assert.ok(css.includes('Needs confirmation'));
  // "Working interpretation" moved from a CSS ::before content string to HTML markup (components/fast-insights.js);
  // see tests/v45.6.9.8-fast-facts-navigation.test.js "customer facts are distinct from working interpretation" for the live check.
});
test('one or two immediate examples remain visible and three or more rely on carousel behavior',()=>{const css=read('components.visual-examples.css');assert.ok(css.includes(':nth-child(n+3)'));assert.ok(css.includes('.illustration-carousel'));});
test('density CSS preserves narrow and forced-colors behavior',()=>{const css=read('components.visual-examples.css');assert.ok(css.includes('@media(max-width:760px)'));assert.ok(css.includes('@media(forced-colors:active)'));});
test('no eligibility decision or persistence files are modified by the density contract',()=>{const s=read('components/question-inline-response.js')+read('components/fast-facts-workspace.js');assert.doesNotMatch(s,/DocumentGuidanceEngine\.evaluate|ProgressiveVisuals\.derive|setCanonicalAnswer|persistDraft|scheduleDraftSave/);});
test('release metadata follows builder version',()=>{const v=(read('build.js').match(/const RELEASE_VERSION='([^']+)'/)||[])[1];assert.ok(v);assert.ok(read('index.html').includes(v));});
