"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const R=path.resolve(__dirname,".."),read=f=>fs.readFileSync(path.join(R,f),"utf8");
function load(f,key){const box={module:{exports:{}},exports:{}};vm.runInNewContext(read(f),box);return box.module.exports||box[key];}
// Retired 2026-10-03: the RELEASE_VERSION='V45.7.5.8' pin is superseded now the build is on V45.7.5.9.9.
test("canonical JADU evaluation explicitly fails separate meter eligibility closed",()=>{const e=load("core/v45.7-correctness-engine.js","V457CorrectnessEngine"),r=e.jadu({aduType:"Junior ADU",aduAddressStatus:"Yes, a separate address is assigned"});assert.equal(r.separateMeterEligible,false);assert.equal(r.separateMeterEligibility,"ineligible");assert.equal(r.meteringText,"A Junior ADU cannot be separately metered.");});
test("JADU result is invariant across every address answer",()=>{const e=load("core/v45.7-correctness-engine.js","V457CorrectnessEngine");for(const a of [undefined,"Yes, a separate address is assigned","The address request is in progress","No separate address is assigned","I’m not sure"])assert.equal(e.jadu({aduType:"Junior ADU",aduAddressStatus:a}).separateMeterEligible,false);});
test("legacy JADU guidance control delegates to the same canonical conclusion",()=>{const c=load("core/jadu-conflict-control.js","JaduConflictControl"),r=c.apply({answers:{aduType:"Junior ADU"}});assert.equal(r.ruleId,"ADU.JADU.METERING");assert.equal(r.separateMeterEligible,false);assert.equal(r.message,"A Junior ADU cannot be separately metered.");});
test("runtime JADU files contain no conditional fallback wording",()=>{for(const f of ["core/jadu-conflict-control.js","core/v45.7-correctness-engine.js"])assert.doesNotMatch(read(f),/may depend on the project details/i);});
test("addressed detached ADU using existing meter and service is detected",()=>{const e=load("core/v45.7-correctness-engine.js","V457CorrectnessEngine"),r=e.aduCompatibility({aduType:"Detached ADU",aduAddressStatus:"Yes, a separate address is assigned",aduMeterServiceIntent:"Use the existing meter and service"});assert.equal(r.status,"incompatible");assert.equal(r.reasonCode,"DETACHED_ADU_SEPARATE_ADDRESS_EXISTING_SERVICE_CONFLICT");assert.equal(r.suppressAffirmativeServiceGuidance,true);});
test("existing no-address separate-service conflict remains detected",()=>{const e=load("core/v45.7-correctness-engine.js","V457CorrectnessEngine"),r=e.aduCompatibility({aduType:"Detached ADU",aduAddressStatus:"No separate address is assigned",aduMeterServiceIntent:"Add a separate service connection"});assert.equal(r.status,"incompatible");assert.equal(r.reasonCode,"DETACHED_ADU_SECOND_SERVICE_ADDRESS_CONFLICT");});
test("permit model separates applicant from issuing authority",()=>{const e=load("core/v45.7-correctness-engine.js","V457CorrectnessEngine"),r=e.permit({projectType:"adu"});assert.match(r.applicant,/homeowner, contractor, electrician/);assert.match(r.issuingAuthority,/city or county authority having jurisdiction/);assert.equal(r.solarSpecificReasoningAllowed,false);});
test("Energy Needs and opening property remain outside active intake",()=>{const s=read("core/v45.7-intake-simplification.js");assert.match(s,/q&&q\.id!==\'energy\'/);assert.match(s,/root\.S\.step=1;root\.S\.questionIndex=0/);});
test("locked photo comparison and document carousel remain",()=>{assert.match(read("components/visual-guidance-card.js"),/function reveal\(i,behavior\)/);assert.match(read("components/fast-facts-document-gallery.js"),/data-document-gallery-step=\"next\"/);});
