'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),model=require('../core/shadow-rule-model.js'),catalog=require('../data/shadow-rule-catalog.js');
function evalFor(projectType,answers={},skipped=[]){return model.evaluate({projectType,answers,skipped},catalog);}
function rule(result,id){return result.rules.find(r=>r.id===id);}
test('catalog validates and rejects missing ownership, duplicate id, unknown path and premature release',()=>{assert.equal(model.validate(catalog),true);for(const mutate of [c=>c.rules.push({...c.rules[0]}),c=>{delete c.rules[0].source.owner},c=>{c.rules[0].factPaths=['panel.bad']},c=>{c.rules[0].release='customer_visible'}]){const c=structuredClone(catalog);mutate(c);assert.throws(()=>model.validate(c));}});
test('unknown, not sure, skipped, unanswered, and false are distinct',()=>{for(const [answer,skipped,state] of [['',[], 'unanswered'],['I’m not sure',[],'not_sure'],['',['panelIntent'],'skipped']]){const r=evalFor('panel',{panelIntent:answer},skipped);assert.equal(r.facts['panel.intent'].state,state);assert.equal(rule(r,'SHADOW-PANEL-UPGRADE-INTENT').truth,'unknown');assert.equal(rule(r,'SHADOW-PANEL-UPGRADE-INTENT').state,'withheld_unknown');}const r=evalFor('panel',{panelIntent:'Replace the panel at the same capacity'});assert.equal(rule(r,'SHADOW-PANEL-UPGRADE-INTENT').truth,'false');assert.equal(rule(r,'SHADOW-PANEL-REPLACE-INTENT').truth,'true');});
test('numeric threshold is false/true/unknown and never coerces missing to zero',()=>{const pred={op:'gte',path:'panel.proposedAmps',value:320};for(const [answer,expected] of [['', 'unknown'],['I’m not sure','unknown'],['More than 200 amps','unknown'],['200 amps','false'],['320 amps','true'],['400 amps or more','unknown']]){const a=model.adapt({projectType:'panel',answers:{panelProposedCapacity:answer}});assert.equal(model.predicate(pred,a.facts),expected,answer);}const a=model.adapt({projectType:'panel',answers:{panelProposedCapacity:'320 amps'}});assert.equal(a.facts['panel.proposedAmps'].value,320);});
test('three-valued all, any, not retain unknown',()=>{const f=model.adapt({projectType:'panel',answers:{panelIntent:'Increase the panel capacity'}}).facts,yes={op:'eq',path:'panel.intent',value:'upgrade'},no={op:'eq',path:'panel.intent',value:'replace'},unknown={op:'eq',path:'panel.proposedAmps',value:320};assert.equal(model.predicate({op:'all',of:[yes,unknown]},f),'unknown');assert.equal(model.predicate({op:'all',of:[no,unknown]},f),'false');assert.equal(model.predicate({op:'any',of:[no,unknown]},f),'unknown');assert.equal(model.predicate({op:'any',of:[yes,unknown]},f),'true');assert.equal(model.predicate({op:'not',of:unknown},f),'unknown');});
test('correction and project switch clear incompatible shadow facts without mutating input',()=>{const input={projectType:'panel',answers:{panelIntent:'Increase the panel capacity',panelProposedCapacity:'320 amps'}};const before=structuredClone(input);let r=model.updateFacts(input,{path:'panel.intent',value:'replace'},catalog);assert.deepEqual(input,before);assert.equal(r.facts['panel.proposedAmps'].state,'invalidated');assert.equal(r.facts['panel.proposedAmps'].value,null);assert.equal(rule(r,'SHADOW-PANEL-REPLACE-INTENT').truth,'true');r=model.updateFacts(r,{path:'project.type',value:'adu'},catalog);assert.equal(r.facts['panel.intent'].state,'not_applicable');assert.equal(r.facts['adu.type'].state,'unanswered');assert.equal(rule(r,'SHADOW-PANEL-REPLACE-INTENT').state,'not_applicable');assert.throws(()=>model.updateFacts(r,{path:'panel.intent',value:'upgrade'},catalog));});
test('order-independent evaluation and stable restoration; never emits customer guidance',()=>{const s={projectType:'adu',answers:{aduType:'Detached ADU',panelIntent:'Relocate the panel'}};const first=model.evaluate(s,catalog),second=model.evaluate(JSON.parse(JSON.stringify(s)),{...catalog,rules:catalog.rules.slice().reverse()});assert.deepEqual(first,second);assert.equal(first.facts['panel.intent'].state,'not_applicable');assert.deepEqual(first.customerGuidance,[]);assert.equal(first.ruleSetVersion,'shadow-v1');});
test('legacy recomputation and serialized inputs remain unchanged with shadow integration',()=>{const ctx=vm.createContext({});for(const f of ['core/answer-state-model.js','core/provenance-model.js','core/state-compatibility.js','core/source-rule-registry.js','core/jadu-conflict-control.js','core/recomputation-pipeline.js','core/persistence-reconstruction.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);const state={projectType:'panel',answers:{panelIntent:'Increase the panel capacity',panelExistingCapacity:'100 amps',panelProposedCapacity:'200 amps',panelLoads:[]},skipped:[],rejected:[],invalidatedAnswers:{}};const baseline=JSON.stringify(ctx.RecomputationPipeline.recompute(state));const legacy=ctx.RecomputationPipeline.apply(state);assert.equal(JSON.stringify(legacy),baseline);const draft=JSON.parse(ctx.PersistenceReconstruction.serialize(state));assert.equal(Object.hasOwn(draft,'shadowDerived'),false);assert.equal(Object.hasOwn(draft,'shadowDiagnostics'),false);assert.equal(Object.hasOwn(draft,'derived'),false);const shadowCtx=vm.createContext({});for(const f of ['data/shadow-rule-catalog.js','core/shadow-rule-model.js','core/answer-state-model.js','core/provenance-model.js','core/state-compatibility.js','core/source-rule-registry.js','core/jadu-conflict-control.js','core/recomputation-pipeline.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),shadowCtx);const clone=structuredClone({projectType:'panel',answers:draft.answers,skipped:[],rejected:[],invalidatedAnswers:{}});const actual=shadowCtx.RecomputationPipeline.apply(clone);assert.equal(JSON.stringify(actual),baseline);assert.equal(shadowCtx.ShadowRuleDiagnostics.mode,'shadow');assert.equal(shadowCtx.ShadowRuleDiagnostics.rules.length,catalog.rules.length);});
test('unrecognized legacy intent fails closed instead of becoming a known negative',()=>{const r=evalFor('panel',{panelIntent:'unmapped old label'});assert.equal(r.facts['panel.intent'].state,'unanswered');assert.equal(rule(r,'SHADOW-PANEL-REPLACE-INTENT').truth,'unknown');});
test('shadow evaluation failure does not block the legacy recomputation',()=>{const ctx=vm.createContext({});for(const f of ['data/shadow-rule-catalog.js','core/shadow-rule-model.js','core/answer-state-model.js','core/provenance-model.js','core/state-compatibility.js','core/source-rule-registry.js','core/jadu-conflict-control.js','core/recomputation-pipeline.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);ctx.ShadowRuleCatalog.rules[0].release='invalid';const s={projectType:'adu',answers:{aduType:'Detached ADU'},skipped:[],invalidatedAnswers:{}};assert.ok(ctx.RecomputationPipeline.apply(s).classification);assert.equal(ctx.ShadowRuleDiagnostics.error,'shadow_evaluation_failed');});
