'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const ctx=vm.createContext({esc});for(const f of ['data/visual-example-catalog.js','data/learning-card-registry.js','components/fast-insights.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);function page(project,property){return ctx.FastInsights.render({projectType:project,property,nextQuestion:{id:project==='adu'?'aduType':'panelIntent',label:project==='adu'?'What type of unit are you adding?':'What are you planning to do with the electrical panel?'}});}
test('all four supported project and property combinations give preparation and a single CTA',()=>{for(const p of ['adu','panel'])for(const property of ['Single-family home','Not sure']){const h=page(p,property);for(const word of ['Worth having handy','You can prepare','PG&amp;E may evaluate later','Best thing to clarify next','Why we’re asking'])assert.ok(h.includes(word),word);assert.equal((h.match(/data-act="fast-facts-continue"/g)||[]).length,1);assert.doesNotMatch(h,/>NaN</);}});
test('ADU governed benchmark disclosure renders content, not NaN',()=>{const h=page('adu','Not sure');
  // The '01 / USE' / '02 / MODIFY' / '03 / ADD' four-card grid was replaced by a single comparison
  // table in V45.7.5.2 (see tests/v45.7.5.2-comparison-content.test.js "ADU USE MODIFY ADD uses one
  // comparison table"). The benchmark figures and framing below are unrelated to that redesign.
  for(const word of ['$4,831.86','303 calendar days','Historical planning benchmark, not a project forecast.','What type of unit are you adding?'])assert.ok(h.includes(word),word);assert.match(h,/<details[^>]*id="adu-cost-detail"/);});
test('Panel distinguishes four nonselected concepts and does not assign an EA amount',()=>{const h=page('panel','Not sure');for(const word of ['01 / REPLACE','02 / ADD LOAD','03 / UPGRADE','04 / RELOCATE','~40 business days','~34 business days'])assert.ok(h.includes(word),word);assert.doesNotMatch(h,/\$2,500|\$3,500|aria-selected="true"|>NaN</);});
test('safe photos, conditional overhead and no false project determinations',()=>{for(const p of ['adu','panel']){const h=page(p,'Not sure');for(const word of ['Meter close-up','Main breaker','Rating label','Only if your service is overhead','Do not touch equipment'])assert.ok(h.includes(word),word);assert.match(h,/<details[^>]*id="insight-overhead"/);assert.doesNotMatch(h,/Your service is underground|Your transformer is overloaded|You need an SLD/);}});
test('transient 1500ms loading and cancellation on back or project change',()=>{const e=fs.readFileSync(path.join(root,'core/events.js'),'utf8'),q=fs.readFileSync(path.join(root,'screens/screen-questions.js'),'utf8');assert.match(e,/scheduleDraftSave\(\);\},1500\)/);assert.match(e,/"fast-facts-edit":function\(\)\{_pnFastFactsLoading=null/);assert.match(e,/"fast-facts-project":function\(\)\{_pnFastFactsLoading=null/);assert.match(q,/role="status"/);});
test('invalid project fails closed',()=>{assert.equal(ctx.FastInsights.render({projectType:'ev',property:'Not sure',nextQuestion:{id:'x',label:'x'}}),'');});
