'use strict';
/* V45.6.10: nav palette, no-crop, SLD reference examples, option previews, image viewer, carousel. */
const test=require('node:test'),assert=require('node:assert/strict');
const {ctx,read}=require('./_helpers-inline.js');const c=ctx(),UNSURE='I’m not sure';
// 2026-10-06: narrowed to just this section's own rules (previously ran to end-of-file with no
// upper bound, silently sweeping in every later section too) — the question-dropdown thumbnail
// rule added much further down (components.visual-examples.css, ".inline-response__figure img" /
// ".answer-context .visual-example img") intentionally uses object-fit:cover on a small fixed-size
// thumbnail, which is a different, later feature this "illustrations never crop" contract was never
// meant to cover (the full image is still shown uncropped when that thumbnail is clicked open).
const css=read('components.visual-examples.css'),block=(css.split('V45.6.10 VISUAL REFINEMENTS')[1]||'').split('V45.6.11 SHARED CAROUSEL')[0];
test('navigation uses PG&E tokens, not legacy purple',()=>{assert.match(block,/--pn-nav-selected:var\(--tint\);--pn-nav-border:var\(--pg\)/);for(const s of ['.question-nav__button[aria-current="step"]','.understanding-nav__button[aria-current]','.summary-section-nav__button.is-active'])assert.ok(block.includes(s),s);assert.doesNotMatch(block,/#405696|#eef3ff|#5b21b6/i);});
test('illustrations never crop',()=>{assert.match(block,/object-fit:contain!important;height:auto!important/);assert.match(block,/\.dynamic-insight--summary \.insight-visual\{max-height:none!important;overflow:visible!important\}/);assert.doesNotMatch(block,/object-fit:cover/);});
test('reference examples map only to real documents and real assets',()=>{for(const [doc,e] of Object.entries(c.DOCUMENT_REFERENCE_EXAMPLES)){assert.ok(Object.values(c.DOCUMENT_GUIDANCE_CATALOG.documents).some(d=>d.id===doc),doc);for(const id of e.byProjectType?Object.values(e.byProjectType):[e.assetId])assert.ok(c.LearningCardRegistry.byId(id),id);assert.match(e.caption,/Example of what .* looks like\. It is not/);}});
test('SLD example accompanies the released single-line diagram document',()=>{const a={panelIntent:'Increase the panel capacity',panelExistingCapacity:'100 amps',panelProposedCapacity:'400 amps or more'};const m=c.derive('panel','panelCapacityCompare',a);const r=m.referenceExamples.find(x=>x.documentId==='DOC-SLD');assert.ok(r);assert.equal(r.assetId,'SLD-012');assert.equal(r.shownAbove,true);const h=c.QuestionInlineResponse.render(m,'');assert.match(h,/example single-line diagram is shown above/);assert.match(h,/data-reference-id="DOC-006"/);});
test('no reference example without a released document',()=>{const m=c.derive('panel','panelCapacityCompare',{panelIntent:'Increase the panel capacity',panelExistingCapacity:'200 amps',panelProposedCapacity:'200 amps'});assert.ok(!m.referenceExamples.some(x=>x.documentId==='DOC-SLD'||x.documentId==='DOC-CUTSHEET'));});
test('single-line-diagram insight now carries the SLD example',()=>{const r=c.window.INSIGHT_CATALOG?null:null;const src=read('data/insight-catalog.js');assert.match(src,/A single-line diagram may be useful[\s\S]*?visualIds:\['SLD-012'\]/);});
// 2026-10-05: renderPreview() moved from a <details class="option-preview"> accordion to the
// standard (i) term-button + hidden .term-definition reveal (components/question-inline-response.js),
// rendered beside the choice label instead of stacked beneath it (screens/screen-shared.js's
// choiceRadioFieldset() wraps label+this in .choice-option — see the next test).
test('option previews: governed copy, hypothetical, no documents, unsure has no image',()=>{const p=c.QuestionInlineResponseEngine.preview({projectType:'adu',question:c.Q('aduType'),value:'Junior ADU',answers:{}});assert.equal(p.hypothetical,true);assert.deepEqual(Array.from(p.visualIds),['SLD-006']);assert.equal(p.documents,undefined);const u=c.QuestionInlineResponseEngine.preview({projectType:'adu',question:c.Q('aduType'),value:UNSURE,answers:{}});assert.equal(u.visualIds.length,0);const h=c.QuestionInlineResponse.renderPreview(p);assert.match(h,/^<button class="term-button choice-option__info"/);assert.match(h,/aria-expanded="false"/);assert.match(h,/hidden>/);assert.match(h,/Reading this does not select the answer/);assert.match(h,/Example only, if you choose this answer/);});
test('previews are skipped for compound, multi-select, wildcard, and non-focus questions',()=>{const P=x=>c.QuestionInlineResponseEngine.preview(x);assert.equal(P({projectType:'panel',question:c.Q('panelCapacityCompare'),value:'400 amps or more'}),null);assert.equal(P({projectType:'panel',question:c.Q('panelLoads'),value:'EV charger'}),null);assert.equal(P({projectType:'panel',question:c.Q('panelExistingCapacity'),value:'100 amps'}),null);assert.equal(P({projectType:'ev',question:c.Q('aduType'),value:'Junior ADU'}),null);});
// 2026-10-05: a <label> implicitly activates its radio on a click anywhere inside it, including a
// nested button — so the (i) preview button has to be the label's SIBLING, not its child, for
// "reading this does not select the answer" to actually hold. choiceRadioFieldset() now only
// wraps label+preview together (in .choice-option, for side-by-side layout) when o.after exists;
// the label markup itself still closes with </label> before o.after is ever concatenated in.
test('preview renders outside the label so it never toggles the radio',()=>{const s=read('screens/screen-shared.js');assert.match(s,/'<\/label>'\s*\]\.join\(''\);/);assert.match(s,/o\.after \? \('<div class="choice-option">' \+ label \+ o\.after \+ '<\/div>'\) : label/);assert.match(read('screens/screen-questions.js'),/after:optionPreview\(q,item\.value\)/);});
/* 2026-10-05: a native <dialog> (not a plain div) so showModal() promotes it to the browser's top
   layer the same way the scenario guide's own dialog does — a plain div, however high its z-index,
   cannot render above a top-layer element. role="dialog" is no longer asserted: a <dialog> element
   carries that semantic natively, and the markup no longer spells it out. */
test('image viewer: native dialog, top-layer promotion, close paths, focus return, no persistence',()=>{const s=read('components/image-viewer.js');for(const x of ["createElement('dialog')",'showModal','aria-modal','data-image-viewer-close','Escape','returnTo','trap(e)',"setAttribute('role','button')","setAttribute('tabindex','0')"])assert.ok(s.includes(x),x);assert.doesNotMatch(s,/localStorage|sessionStorage|persistDraft|scheduleDraftSave|\bS\.|history\.(push|replace)State/);assert.match(block,/\.image-viewer__frame img\{[^}]*object-fit:contain/);});
test('carousel only at 3+ items, with controls and snap',()=>{const s=read('components/image-viewer.js');assert.match(s,/var MIN=3;/);assert.match(s,/imageCount\(g\)<MIN/);for(const x of ['scroll-snap-type:x mandatory','.illustration-carousel__btn{min-width:44px;min-height:44px'])assert.ok(block.includes(x),x);});
test('build wires the new modules in order and enhancement runs after render',()=>{const b=read('build.js'),pos=f=>b.indexOf("'"+f+"'");const order=['data/document-guidance-catalog.js','data/document-reference-examples.js','data/answer-response-catalog.js','core/document-guidance-engine.js','core/question-inline-response-engine.js','components/document-guidance-card.js','components/question-inline-response.js','components/image-viewer.js','screens/screen-questions.js','core/events.js'];for(let i=0;i<order.length;i++){assert.ok(pos(order[i])>0,order[i]);if(i)assert.ok(pos(order[i])>pos(order[i-1]),order[i]);}assert.match(read('core/events.js'),/pnEnhanceImages\(\);\}/);});
/* Retired 2026-10-03: this pinned RELEASE_VERSION to the V45.6.x era, which no longer holds now that
   the build has moved to V45.7.x. The version-independent half of the contract (index.html's <title>
   matches whatever RELEASE_VERSION currently is) is covered by tests/v45.6.13-visual-guidance-migration.test.js. */
