/* V44.42 deterministic, derived-only guidance model. */
'use strict';
var CANONICAL_SCENARIOS={adu:{existing:'adu-existing-service',meter:'adu-separate-meter',service:'adu-separate-service',unknown:'adu-unknown'},panel:{likeForLike:'panel-like-for-like',increase:'panel-capacity-increase',relocation:'panel-relocation',upstream:'panel-upstream-review',unknown:'panel-unknown'}};
var GUIDANCE_DISCLOSURES={historical:'Historical planning reference. This is a historical average, not a quote or project commitment. Individual projects vary.',express:'Express-path guidance only. It does not apply to every project, and no countdown has started.'};
var TIMING_BENCHMARKS=[
{id:'adu-separate-service-historical',scenarioIds:['adu-separate-service'],kind:'historical-average',value:303,unit:'calendar days',sourceId:'SB1210-2025-ADU',lastValidated:'2026-09-02',customerSafe:true,disclosureId:'historical',prohibitedUses:['quote','commitment','project forecast']},
{id:'panel-public-historical',scenarioIds:['panel-capacity-increase','panel-relocation','panel-upstream-review'],kind:'historical-average',values:{pgeControlled:34,endToEnd:40},unit:'business days',sourceId:'PANEL-PUBLIC-HISTORICAL',lastValidated:'2026-09-02',customerSafe:true,disclosureId:'historical',prohibitedUses:['quote','commitment','project forecast']},
{id:'express-document-window',scenarioIds:['adu-existing-service','adu-separate-meter','panel-like-for-like','panel-capacity-increase'],kind:'process-window',value:19,unit:'calendar days',sourceId:'EXPRESS-DOC-WINDOW',lastValidated:'2026-09-02',customerSafe:true,requires:'expressEligible',disclosureId:'express',prohibitedUses:['universal deadline','countdown before application']}];
function deriveScenarioId(state){var s=state||S,a=s.answers||{};if(s.projectType==='adu'){if(a.aduMeterServiceIntent==='Add a separate service connection')return CANONICAL_SCENARIOS.adu.service;if(a.aduMeterServiceIntent==='Add a separate meter')return CANONICAL_SCENARIOS.adu.meter;if(a.aduMeterServiceIntent==='Use the existing meter and service')return CANONICAL_SCENARIOS.adu.existing;return CANONICAL_SCENARIOS.adu.unknown;}if(s.projectType==='panel'){if(a.panelIntent==='Replace the panel at the same capacity')return CANONICAL_SCENARIOS.panel.likeForLike;if(a.panelIntent==='Relocate the panel')return CANONICAL_SCENARIOS.panel.relocation;if(a.panelIntent==='Increase the panel capacity')return CANONICAL_SCENARIOS.panel.increase;return CANONICAL_SCENARIOS.panel.unknown;}return 'unknown';}
function eligibleTimingBenchmarks(state,scenarioId){var facts=(state&&state.derivedFacts)||{};return TIMING_BENCHMARKS.filter(function(b){return b.customerSafe&&b.scenarioIds.indexOf(scenarioId)>=0&&(!b.requires||(b.requires==='expressEligible'&&facts.expressEligible===true));}).map(function(b){var x=Object.assign({},b);x.disclosure=GUIDANCE_DISCLOSURES[b.disclosureId]||'';return x;});}
function deriveCustomerGuidance(state){var s=state||S,I=interpret(),scenarioId=deriveScenarioId(s),timing=eligibleTimingBenchmarks(s,scenarioId);return {scenarioId:scenarioId,known:(I.known||[]).slice(),confirmation:(I.confirm||[]).slice(),possible:(I.mayNeed||[]).slice(),delays:(I.timeline||[]).slice(),questions:(I.questions||[]).slice(),recommendedNextAction:{action:I.recommendation||'',who:I.owner||'',why:I.why||'',after:I.after||''},timingBenchmarks:timing,disclosures:timing.map(function(x){return x.disclosure;}).filter(function(x,i,a){return x&&a.indexOf(x)===i;}),interpretation:I.projectLabel||'',consistency:(I.consistency||[]).slice()};}
if(typeof module!=='undefined'&&module.exports)module.exports={CANONICAL_SCENARIOS:CANONICAL_SCENARIOS,TIMING_BENCHMARKS:TIMING_BENCHMARKS,deriveScenarioId:deriveScenarioId,eligibleTimingBenchmarks:eligibleTimingBenchmarks,deriveCustomerGuidance:deriveCustomerGuidance};

;

/* D9A conflict-control overlay; never an eligibility derivation. */
function jaduConflictGuidance(runtime){return typeof JaduConflictControl!=="undefined"?JaduConflictControl.apply(runtime||S):null;}
