/* ============================ STEP 0 — single project selection ============================ */
function helpfulDefinitionTerm(label,detail){var definition=(typeof GLOSSARY!=="undefined"&&(GLOSSARY[label]||GLOSSARY[String(label).toLowerCase()]))?(GLOSSARY[label]||GLOSSARY[String(label).toLowerCase()]):"";termDisclosureSequence+=1;var id="helpful-context-"+String(label).toLowerCase().replace(/\W+/g,"-")+"-"+termDisclosureSequence;return '<article class="helpful-definition"><div class="helpful-definition__standing"><h3>'+esc(label)+'</h3><p>'+esc(definition)+'</p></div><button class="term-button helpful-definition__info" type="button" data-definition-action="project-context" data-term-label="'+esc(label)+'" aria-expanded="false" aria-controls="'+esc(id)+'" aria-label="Show why '+esc(label)+' matters for this project"><span class="term-button__cue" aria-hidden="true">i</span></button><div id="'+esc(id)+'" class="term-definition helpful-definition__reveal" role="status" aria-live="polite" hidden><strong>Why this matters for your project</strong><p>'+esc(detail)+'</p></div></article>';}
function step0(){
  var cand=S.discoverCandidates||[],guessSet={};cand.forEach(function(id){guessSet[id]=1;});
  var choices=[
    {id:"adu",title:"Accessory dwelling unit, or ADU",subtitle:"Add a separate living space on the same property",icon:"home"},
    {id:"panel",title:"Panel upgrade",subtitle:"Replace, increase, or relocate an electrical panel",icon:"gauge"},
    {id:"other",title:"Other projects, coming soon",subtitle:"Additional project types will be added over time",icon:"wrench",disabled:true},
    {id:"unsure",title:"I’m not sure",subtitle:"Describe the project in your own words",icon:"circle-help"}
  ];
  var opts=choices.map(function(x){var on=S.projectType===x.id,isGuess=!!guessSet[x.id];if(x.disabled)return '<button class="opt opt--frozen" type="button" aria-disabled="true" disabled><span class="ico">'+icon(x.icon,22)+'</span><span class="tt"><strong>'+esc(x.title)+'</strong><small>'+esc(x.subtitle)+'</small></span><span class="opt__frozen-badge">Coming soon</span></button>';return '<button class="opt'+(on?' active':'')+'" type="button" role="radio" aria-checked="'+on+'" data-act="ptype" data-id="'+x.id+'"><span class="ico">'+icon(x.icon,22)+'</span><span class="tt"><strong>'+esc(x.title)+'</strong><small>'+esc(x.subtitle)+'</small></span>'+(isGuess&&!on?'<span class="sugg">Suggested</span>':'<span data-project-mark>'+(on?icon("check",20):icon("arrow-right",18))+'</span>')+'</button>';}).join('');
  var discover=S.projectType==="unsure"?'<section class="discovery" aria-labelledby="discover-heading"><h2 id="discover-heading">Tell us anything else that would help us understand your project.</h2><p class="muted">Additional details are optional. You can continue without adding more.</p><label class="sr" for="discoverInput">Project details</label><textarea id="discoverInput" data-act="discover-input" rows="3" placeholder="For example: I want to add electrical equipment, but I’m not sure which project type fits.">'+esc(S.discoverText||'')+'</textarea><div class="rowact"><button class="btn secondary" data-act="discover-guess" type="button">'+icon("sparkles",16)+'Suggest a starting point</button><button class="btn primary" data-act="go" data-step="1" type="button">Continue with focused questions '+icon("arrow-right",16)+'</button></div></section>':'';
  return '<section class="col project-choice-first" aria-labelledby="project-choice-heading"><div class="eyebrow">Choose a residential project</div><h1 class="big" id="project-choice-heading">What residential project would you like to explore?</h1><p class="lede">Choose the project scenario closest to what you want to explore. Project Navigator will ask a few questions and build early preparation guidance based on your answers.</p><div data-project-options role="radiogroup" aria-label="Project type">'+opts+'</div>'+(S.projectType==='adu'||S.projectType==='panel'?'<div class="project-choice-first__continue"><button class="btn primary" type="button" data-act="project-continue">See fast facts '+icon("arrow-right",16)+'</button><p>Your project choice is saved. Next, review fast facts before the focused questions.</p></div>':'')+discover+'<details class="context-definitions"><summary><span>Helpful definitions</span><small>3 terms</small></summary><div class="context-definitions__terms">'+helpfulDefinitionTerm("Electrical panel","A licensed electrician can combine the main-breaker rating with planned equipment and a code-based load calculation. This helps test whether the existing panel can support the project before a larger panel is assumed.")+helpfulDefinitionTerm("Meter","Meter count does not answer whether a separate utility service is needed. Confirm whether the project shares the existing service, needs another meter, or requires utility planning before designing around either option.")+helpfulDefinitionTerm("Service upgrade","A panel replacement and a utility service upgrade are different scopes. A load calculation and site review help identify which scope, if either, needs to be discussed with the contractor or PG&E.")+'</div><button class="linkbtn context-definitions__all" type="button" id="glossaryBtnInline" data-act="open-glossary">View all definitions</button></details><div class="note project-boundary"><span><strong>Early preparation guidance.</strong> This is not an application, approval, final project determination, or commitment on cost or schedule.</span></div></section>';
}

;

;
